version: '3.8'

services:

  postgres:
    restart: "no" #"no" always on-failure unless-stopped
    image: postgres:latest
    container_name: postgres
    ports:
      - 127.0.0.1:7432:5432/tcp
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bergen-tech
    volumes:
      - ./internal/pg/data:/var/lib/postgresql
      # BUG - ./internal/pg/data:/var/lib/postgresql/data #BUG chmod on #folder ./internal/pg/data from conteiner, next run ERROR access!
      

  bergen-tech:
    depends_on:
      - postgres
    build:
      context: ./
      dockerfile: Dockerfile.bergen-tech
    container_name: bergen-tech
    ports:
    - 127.0.0.1:9090:9090/tcp
    environment:
      GOPATH: /
      HTTP_PORT: :9090
      HTTP_HOST: 127.0.0.1
      LOG_LEVEL: 6
      PG_URL: "postgres://postgres:postgres@postgres/bergen-tech?sslmode=disable"
      PG_MIGRATIONS_PATH: "file://../../internal/pg/migrations"

    command: ["./cmd/job/wait-for-it.sh", "postgres:7432", "--timeout=10", "--", "./bergen-tech", "-loglevel=6"]
    #command: ["./bergen-tech", "-loglevel=6"]
